### ISSUE TITLE
The POM for com.smartbear:ready-api-soapui-pro:jar:1.2.0 is missing, no dependency information available

### ISSUE THREAD

**Issue by vkovryga** [SmartBear/ready-api-plugins#1]
Hi, I get this error (hopefully it can be fixed quick):

$ mvn install
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=1024M; support was removed in 8.0
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option PermSize=512m; support was removed in 8.0
[INFO] Scanning for projects...
[INFO]
[INFO] Using the builder org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder with a thread count of 1
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Ready! API Action Plugin 1.0.0
[INFO] ------------------------------------------------------------------------
Downloading: http://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-compiler-plugin/3.1/maven-compiler-plugin-3.1.pom
Downloaded: http://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-compiler-plugin/3.1/maven-compiler-plugin-3.1.pom (0 B at 0.0 KB/sec)
Downloading: http://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-compiler-plugin/3.1/maven-compiler-plugin-3.1.jar
Downloaded: http://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-compiler-plugin/3.1/maven-compiler-plugin-3.1.jar (0 B at 0.0 KB/sec)
Downloading: http://www.eviware.com/repository/maven2/org/codehaus/gmaven/runtime/gmaven-runtime-1.8/1.5/gmaven-runtime-1.8-1.5.pom
Downloading: http://repo1.maven.org/maven2/org/codehaus/gmaven/runtime/gmaven-runtime-1.8/1.5/gmaven-runtime-1.8-1.5.pom
Downloaded: http://repo1.maven.org/maven2/org/codehaus/gmaven/runtime/gmaven-runtime-1.8/1.5/gmaven-runtime-1.8-1.5.pom (4 KB at 22.4 KB/sec)
Downloading: http://www.eviware.com/repository/maven2/org/codehaus/gmaven/runtime/gmaven-runtime/1.5/gmaven-runtime-1.5.pom
Downloading: http://repo1.maven.org/maven2/org/codehaus/gmaven/runtime/gmaven-runtime/1.5/gmaven-runtime-1.5.pom
Downloaded: http://repo1.maven.org/maven2/org/codehaus/gmaven/runtime/gmaven-runtime/1.5/gmaven-runtime-1.5.pom (0 B at 0.0 KB/sec)
Downloading: http://www.eviware.com/repository/maven2/org/codehaus/gmaven/gmaven/1.5/gmaven-1.5.pom
Downloading: http://repo1.maven.org/maven2/org/codehaus/gmaven/gmaven/1.5/gmaven-1.5.pom
Downloaded: http://repo1.maven.org/maven2/org/codehaus/gmaven/gmaven/1.5/gmaven-1.5.pom (0 B at 0.0 KB/sec)
Downloading: http://www.eviware.com/repository/maven2/org/slf4j/slf4j-api/1.5.10/slf4j-api-1.5.10.pom
Downloading: http://repo1.maven.org/maven2/org/slf4j/slf4j-api/1.5.10/slf4j-api-1.5.10.pom
Downloaded: http://repo1.maven.org/maven2/org/slf4j/slf4j-api/1.5.10/slf4j-api-1.5.10.pom (0 B at 0.0 KB/sec)
Downloading: http://www.eviware.com/repository/maven2/org/slf4j/slf4j-parent/1.5.10/slf4j-parent-1.5.10.pom
Downloading: http://repo1.maven.org/maven2/org/slf4j/slf4j-parent/1.5.10/slf4j-parent-1.5.10.pom
Downloaded: http://repo1.maven.org/maven2/org/slf4j/slf4j-parent/1.5.10/slf4j-parent-1.5.10.pom (0 B at 0.0 KB/sec)
Downloading: http://www.eviware.com/repository/maven2/org/codehaus/gmaven/feature/gmaven-feature-support/1.5/gmaven-feature-support-1.5.pom
Downloading: http://repo1.maven.org/maven2/org/codehaus/gmaven/feature/gmaven-feature-support/1.5/gmaven-feature-support-1.5.pom
Downloaded: http://repo1.maven.org/maven2/org/codehaus/gmaven/feature/gmaven-feature-support/1.5/gmaven-feature-support-1.5.pom (0 B at 0.0 KB/sec)
Downloading: http://www.eviware.com/repository/maven2/org/codehaus/gmaven/feature/gmaven-feature/1.5/gmaven-feature-1.5.pom
Downloading: http://repo1.maven.org/maven2/org/codehaus/gmaven/feature/gmaven-feature/1.5/gmaven-feature-1.5.pom
Downloaded: http://repo1.maven.org/maven2/org/codehaus/gmaven/feature/gmaven-feature/1.5/gmaven-feature-1.5.pom (0 B at 0.0 KB/sec)
Downloading: http://www.eviware.com/repository/maven2/org/codehaus/gmaven/feature/gmaven-feature-api/1.5/gmaven-feature-api-1.5.pom
Downloading: http://repo1.maven.org/maven2/org/codehaus/gmaven/feature/gmaven-feature-api/1.5/gmaven-feature-api-1.5.pom
Downloaded: http://repo1.maven.org/maven2/org/codehaus/gmaven/feature/gmaven-feature-api/1.5/gmaven-feature-api-1.5.pom (0 B at 0.0 KB/sec)
Downloading: http://www.eviware.com/repository/maven2/org/codehaus/gmaven/runtime/gmaven-runtime-support/1.5/gmaven-runtime-support-1.5.pom
Downloading: http://repo1.maven.org/maven2/org/codehaus/gmaven/runtime/gmaven-runtime-support/1.5/gmaven-runtime-support-1.5.pom
Downloaded: http://repo1.maven.org/maven2/org/codehaus/gmaven/runtime/gmaven-runtime-support/1.5/gmaven-runtime-support-1.5.pom (0 B at 0.0 KB/sec)
Downloading: http://www.eviware.com/repository/maven2/org/codehaus/gmaven/runtime/gmaven-runtime-api/1.5/gmaven-runtime-api-1.5.pom
Downloading: http://repo1.maven.org/maven2/org/codehaus/gmaven/runtime/gmaven-runtime-api/1.5/gmaven-runtime-api-1.5.pom
Downloaded: http://repo1.maven.org/maven2/org/codehaus/gmaven/runtime/gmaven-runtime-api/1.5/gmaven-runtime-api-1.5.pom (0 B at 0.0 KB/sec)
Downloading: http://www.eviware.com/repository/maven2/org/sonatype/gshell/gshell-io/2.4/gshell-io-2.4.pom
Downloading: http://repo1.maven.org/maven2/org/sonatype/gshell/gshell-io/2.4/gshell-io-2.4.pom
Downloaded: http://repo1.maven.org/maven2/org/sonatype/gshell/gshell-io/2.4/gshell-io-2.4.pom (0 B at 0.0 KB/sec)
Downloading: http://www.eviware.com/repository/maven2/org/sonatype/gshell/gshell/2.4/gshell-2.4.pom
Downloading: http://repo1.maven.org/maven2/org/sonatype/gshell/gshell/2.4/gshell-2.4.pom
Downloaded: http://repo1.maven.org/maven2/org/sonatype/gshell/gshell/2.4/gshell-2.4.pom (0 B at 0.0 KB/sec)
Downloading: http://www.eviware.com/repository/maven2/org/sonatype/gossip/gossip/1.3/gossip-1.3.pom
Downloading: http://repo1.maven.org/maven2/org/sonatype/gossip/gossip/1.3/gossip-1.3.pom
Downloaded: http://repo1.maven.org/maven2/org/sonatype/gossip/gossip/1.3/gossip-1.3.pom (0 B at 0.0 KB/sec)
Downloading: http://jansi.fusesource.org/repo/release/org/sonatype/gossip/gossip/1.3/gossip-1.3.pom
Downloading: http://www.eviware.com/repository/maven2/com/thoughtworks/qdox/qdox/1.12/qdox-1.12.pom
Downloading: http://repo1.maven.org/maven2/com/thoughtworks/qdox/qdox/1.12/qdox-1.12.pom
Downloaded: http://repo1.maven.org/maven2/com/thoughtworks/qdox/qdox/1.12/qdox-1.12.pom (0 B at 0.0 KB/sec)
Downloading: http://www.eviware.com/repository/maven2/org/codehaus/groovy/groovy-all/1.8.7/groovy-all-1.8.7.pom
Downloading: http://repo1.maven.org/maven2/org/codehaus/groovy/groovy-all/1.8.7/groovy-all-1.8.7.pom
Downloaded: http://repo1.maven.org/maven2/org/codehaus/groovy/groovy-all/1.8.7/groovy-all-1.8.7.pom (31 KB at 133.7 KB/sec)
Downloading: http://www.eviware.com/repository/maven2/org/apache/ant/ant/1.8.2/ant-1.8.2.pom
Downloading: http://repo1.maven.org/maven2/org/apache/ant/ant/1.8.2/ant-1.8.2.pom
Downloaded: http://repo1.maven.org/maven2/org/apache/ant/ant/1.8.2/ant-1.8.2.pom (10 KB at 119.1 KB/sec)
Downloading: http://www.eviware.com/repository/maven2/org/apache/ant/ant-parent/1.8.2/ant-parent-1.8.2.pom
Downloading: http://repo1.maven.org/maven2/org/apache/ant/ant-parent/1.8.2/ant-parent-1.8.2.pom
Downloaded: http://repo1.maven.org/maven2/org/apache/ant/ant-parent/1.8.2/ant-parent-1.8.2.pom (5 KB at 55.8 KB/sec)
Downloading: http://www.eviware.com/repository/maven2/org/apache/ant/ant-launcher/1.8.2/ant-launcher-1.8.2.pom
Downloading: http://repo1.maven.org/maven2/org/apache/ant/ant-launcher/1.8.2/ant-launcher-1.8.2.pom
Downloaded: http://repo1.maven.org/maven2/org/apache/ant/ant-launcher/1.8.2/ant-launcher-1.8.2.pom (3 KB at 26.5 KB/sec)
Downloading: http://www.eviware.com/repository/maven2/jline/jline/0.9.94/jline-0.9.94.pom
Downloaded: http://www.eviware.com/repository/maven2/jline/jline/0.9.94/jline-0.9.94.pom (0 B at 0.0 KB/sec)
Downloading: http://repo1.maven.org/maven2/jline/jline/0.9.94/jline-0.9.94.pom
Downloaded: http://repo1.maven.org/maven2/jline/jline/0.9.94/jline-0.9.94.pom (0 B at 0.0 KB/sec)
Downloading: http://www.eviware.com/repository/maven2/com/smartbear/ready-api-soapui-pro/1.2.0/ready-api-soapui-pro-1.2.0.pom
Downloading: http://repo1.maven.org/maven2/com/smartbear/ready-api-soapui-pro/1.2.0/ready-api-soapui-pro-1.2.0.pom
[WARNING] The POM for com.smartbear:ready-api-soapui-pro:jar:1.2.0 is missing, no dependency information available
Downloading: http://www.eviware.com/repository/maven2/org/codehaus/gmaven/runtime/gmaven-runtime-1.8/1.5/gmaven-runtime-1.8-1.5.jar
Downloading: http://www.eviware.com/repository/maven2/org/slf4j/slf4j-api/1.5.10/slf4j-api-1.5.10.jar
Downloading: http://www.eviware.com/repository/maven2/org/codehaus/gmaven/feature/gmaven-feature-support/1.5/gmaven-feature-support-1.5.jar
Downloading: http://www.eviware.com/repository/maven2/org/codehaus/gmaven/feature/gmaven-feature-api/1.5/gmaven-feature-api-1.5.jar
Downloading: http://www.eviware.com/repository/maven2/org/codehaus/gmaven/runtime/gmaven-runtime-support/1.5/gmaven-runtime-support-1.5.jar
Downloading: http://www.eviware.com/repository/maven2/org/codehaus/gmaven/runtime/gmaven-runtime-api/1.5/gmaven-runtime-api-1.5.jar
Downloading: http://www.eviware.com/repository/maven2/org/sonatype/gshell/gshell-io/2.4/gshell-io-2.4.jar
Downloading: http://www.eviware.com/repository/maven2/org/sonatype/gossip/gossip/1.3/gossip-1.3.jar
Downloading: http://www.eviware.com/repository/maven2/com/thoughtworks/qdox/qdox/1.12/qdox-1.12.jar
Downloading: http://www.eviware.com/repository/maven2/org/codehaus/groovy/groovy-all/1.8.7/groovy-all-1.8.7.jar
Downloading: http://www.eviware.com/repository/maven2/org/apache/ant/ant/1.8.2/ant-1.8.2.jar
Downloading: http://www.eviware.com/repository/maven2/org/apache/ant/ant-launcher/1.8.2/ant-launcher-1.8.2.jar
Downloading: http://www.eviware.com/repository/maven2/jline/jline/0.9.94/jline-0.9.94.jar
Downloading: http://www.eviware.com/repository/maven2/com/smartbear/ready-api-soapui-pro/1.2.0/ready-api-soapui-pro-1.2.0.jar
Downloaded: http://www.eviware.com/repository/maven2/jline/jline/0.9.94/jline-0.9.94.jar (0 B at 0.0 KB/sec)
Downloading: http://repo1.maven.org/maven2/org/codehaus/gmaven/runtime/gmaven-runtime-1.8/1.5/gmaven-runtime-1.8-1.5.jar
Downloading: http://repo1.maven.org/maven2/org/slf4j/slf4j-api/1.5.10/slf4j-api-1.5.10.jar
Downloading: http://repo1.maven.org/maven2/org/codehaus/gmaven/feature/gmaven-feature-api/1.5/gmaven-feature-api-1.5.jar
Downloading: http://repo1.maven.org/maven2/org/codehaus/gmaven/runtime/gmaven-runtime-support/1.5/gmaven-runtime-support-1.5.jar
Downloading: http://repo1.maven.org/maven2/org/codehaus/gmaven/feature/gmaven-feature-support/1.5/gmaven-feature-support-1.5.jar
Downloaded: http://repo1.maven.org/maven2/org/codehaus/gmaven/feature/gmaven-feature-support/1.5/gmaven-feature-support-1.5.jar (0 B at 0.0 KB/sec)
Downloaded: http://repo1.maven.org/maven2/org/slf4j/slf4j-api/1.5.10/slf4j-api-1.5.10.jar (0 B at 0.0 KB/sec)
Downloading: http://repo1.maven.org/maven2/org/sonatype/gshell/gshell-io/2.4/gshell-io-2.4.jar
Downloading: http://repo1.maven.org/maven2/org/codehaus/gmaven/runtime/gmaven-runtime-api/1.5/gmaven-runtime-api-1.5.jar
Downloaded: http://repo1.maven.org/maven2/org/codehaus/gmaven/runtime/gmaven-runtime-support/1.5/gmaven-runtime-support-1.5.jar (0 B at 0.0 KB/sec)
Downloaded: http://repo1.maven.org/maven2/org/codehaus/gmaven/feature/gmaven-feature-api/1.5/gmaven-feature-api-1.5.jar (0 B at 0.0 KB/sec)
Downloading: http://repo1.maven.org/maven2/org/sonatype/gossip/gossip/1.3/gossip-1.3.jar
Downloading: http://repo1.maven.org/maven2/com/thoughtworks/qdox/qdox/1.12/qdox-1.12.jar
Downloaded: http://repo1.maven.org/maven2/org/codehaus/gmaven/runtime/gmaven-runtime-1.8/1.5/gmaven-runtime-1.8-1.5.jar (49 KB at 180.3 KB/sec)
Downloading: http://repo1.maven.org/maven2/org/codehaus/groovy/groovy-all/1.8.7/groovy-all-1.8.7.jar
Downloaded: http://repo1.maven.org/maven2/org/sonatype/gshell/gshell-io/2.4/gshell-io-2.4.jar (0 B at 0.0 KB/sec)
Downloading: http://repo1.maven.org/maven2/org/apache/ant/ant/1.8.2/ant-1.8.2.jar
Downloaded: http://repo1.maven.org/maven2/org/codehaus/gmaven/runtime/gmaven-runtime-api/1.5/gmaven-runtime-api-1.5.jar (0 B at 0.0 KB/sec)
Downloading: http://repo1.maven.org/maven2/org/apache/ant/ant-launcher/1.8.2/ant-launcher-1.8.2.jar
Downloaded: http://repo1.maven.org/maven2/com/thoughtworks/qdox/qdox/1.12/qdox-1.12.jar (0 B at 0.0 KB/sec)
Downloading: http://repo1.maven.org/maven2/jline/jline/0.9.94/jline-0.9.94.jar
Downloaded: http://repo1.maven.org/maven2/org/sonatype/gossip/gossip/1.3/gossip-1.3.jar (75 KB at 324.6 KB/sec)
Downloading: http://repo1.maven.org/maven2/com/smartbear/ready-api-soapui-pro/1.2.0/ready-api-soapui-pro-1.2.0.jar
Downloaded: http://repo1.maven.org/maven2/org/apache/ant/ant-launcher/1.8.2/ant-launcher-1.8.2.jar (13 KB at 97.8 KB/sec)
Downloaded: http://repo1.maven.org/maven2/jline/jline/0.9.94/jline-0.9.94.jar (0 B at 0.0 KB/sec)
Downloaded: http://repo1.maven.org/maven2/org/apache/ant/ant/1.8.2/ant-1.8.2.jar (1889 KB at 1768.2 KB/sec)
Downloaded: http://repo1.maven.org/maven2/org/codehaus/groovy/groovy-all/1.8.7/groovy-all-1.8.7.jar (6063 KB at 2371.0 KB/sec)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:40 min
[INFO] Finished at: 2015-06-25T11:08:05-05:00
[INFO] Final Memory: 9M/981M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project my_plugin: Could not resolve dependencies for project com.blackberry:my_plugin:jar:1.0.0: Could not find artifact com.
smartbear:ready-api-soapui-pro:jar:1.2.0 in eviware (http://www.eviware.com/repository/maven2) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**Comment by olensmar** [comment]
Hi!

please try updating the Ready! API dependencies from 1.2.0 to 1.2.1 - does that help?

/Ole

**Comment by vkovryga** [comment]
Yes, that resolved the issue - thank you!
