### ISSUE TITLE
Is there any problem with ready-api-soapui-1.7.0.jar?

### ISSUE THREAD

**Issue by bilgvvn** [SmartBear/ready-api-plugins#4]
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 27.422 s
[INFO] Finished at: 2016-05-05T14:55:35-04:00
[INFO] Final Memory: 14M/205M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project ready-api-plugin-template: Could not r
esolve dependencies for project com.smartbear:ready-api-plugin-template:jar:1.0-
SNAPSHOT: The following artifacts could not be resolved: com.smartbear:ready-api
-soapui:jar:1.7.0, com.smartbear:ready-api-projects:jar:1.0.0: Could not transfe
r artifact com.smartbear:ready-api-soapui:jar:1.7.0 from/to eviware (http://www.
eviware.com/repository/maven2): GET request of: com/smartbear/ready-api-soapui/1
.7.0/ready-api-soapui-1.7.0.jar from eviware failed: Connection reset -> [Help 1
]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e swit
ch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please rea
d the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyReso
lutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command

**Comment by prakashmrec** [comment]
It seems connection issue. Are you able to access http://www.eviware.com/repository/maven2/com/smartbear/ready-api-soapui/1.7.0/ through browser. 
Another problem though is that the ready-api-projects 1.0.0 doesn't exist in public maven repo and pull request https://github.com/SmartBear/ready-api-plugins/pull/5 should resolve that issue. Please try again with the fixes from this pr.

**Comment by bilgvvn** [comment]
thanks for the reply. I am able to access by web browser. But when i try to download .jar file, it fails after half of the file is downloaded.

**Comment by bilgvvn** [comment]
Tried it today and issue was fixed. 

Thanks,
Bil.
